### ISSUE TITLE
Deserialization error on rockset-java-client v. 0.9.4 for error type QueryError

### ISSUE THREAD

**Issue by giacomo-calixa** [rockset/rockset-java-client#37]
See stack trace:

Returned string reads `"type":"QueryError"` while the known values from enum has `QUERY_ERROR`

```
com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `com.rockset.client.model.ErrorModel$TypeEnum` from String "QueryError": not one of the values accepted for Enum class: [RESOURCEEXCEEDED, DEPENDENTRESOURCES, CONNECTION_ERROR, BADREQUEST, INTERNALERROR, ROLE_NOT_FOUND, RATELIMITEXCEEDED, NOTFOUND, QUERY_ERROR, INVALIDINPUT, ALREADYEXISTS, NOTACCEPTABLE, NOT_READY, FORBIDDEN, QUERY_CANCELLED, SERVICEUNAVAILABLE, AUTHEXCEPTION, QUERY_TIMEOUT, NOTALLOWED, VERSIONEXCEPTION, NOTIMPLEMENTEDYET, NOTSUPPORTED, CLIENT_CONNECTION_ERROR, CREATING]
 at [Source: (String)"{"message":"Incorrect SQL syntax near ')'. Please inspect your query for correct syntax.","message_key":null,"type":"QueryError","line":24,"column":77,"trace_id":"xyz","error_id":"","query_id":"xyz"}"; line: 1, column: 117] (through reference chain: com.rockset.client.model.ErrorModel["type"])
    at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67)
    at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:1991)
    at com.fasterxml.jackson.databind.DeserializationContext.handleWeirdStringValue(DeserializationContext.java:1219)
    at com.fasterxml.jackson.databind.deser.std.EnumDeserializer._deserializeAltString(EnumDeserializer.java:356)
    at com.fasterxml.jackson.databind.deser.std.EnumDeserializer._fromString(EnumDeserializer.java:230)
    at com.fasterxml.jackson.databind.deser.std.EnumDeserializer.deserialize(EnumDeserializer.java:198)
    at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:313)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:176)
    at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
    at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4674)
    at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3629)
    at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3597)
    at com.rockset.client.ApiClient.handleResponse(ApiClient.java:903)
    at com.rockset.client.ApiClient.execute(ApiClient.java:819)
    at com.rockset.client.api.QueriesApi.queryWithHttpInfo(QueriesApi.java:647)
    at com.rockset.client.api.QueriesApi.query(QueriesApi.java:633)
    ```
    
    Many thanks!

**Comment by richardlin047** [comment]
This has been addressed in #38 so you will be able to build the latest code and it should no longer appear. v0.9.5 will also be coming soon!
